### ISSUE TITLE
Rolling Stock Relocate/Respawn

### ISSUE THREAD

**Issue by fbane** [JennyKmu/RRO_savefile_editor#26]
Include the location of these if possible as not being named it makes it difficult to know location.

Using Ians map tool it labels one of my cars near 'Iron Mine' which I know is the one that flew away. If you had the location option for rolling stock this could help.

**Comment by JennyKmu** [comment]
We'll do that, though showing coordinates might not help much (especially since X is unintuitively towards West instead of East, while Z is still above, so the coordinate system is not direct, which bothers me a lot). Maybe it will have to wait until I get a Track Map sorted, we'll see what we can do.

**Comment by JennyKmu** [comment]
This will be addressed with #7 combined with #43
